export const summary = {
  income: 235000,
  expense: 128450,
  balance: 106550,
  fixedExpense: 65300,
};

export const categories = [
  {
    id: "cat-food",
    name: "吃喝",
    emoji: "🍔",
    type: "expense",
    color: "#f97316",
  },
  {
    id: "cat-daily",
    name: "日常",
    emoji: "🧻",
    type: "expense",
    color: "#64748b",
  },
  {
    id: "cat-housing",
    name: "住房",
    emoji: "🏠",
    type: "expense",
    color: "#5b8def",
  },
  {
    id: "cat-insurance",
    name: "保險",
    emoji: "🛡️",
    type: "expense",
    color: "#f6b85a",
  },
  {
    id: "cat-car-transport",
    name: "汽車交通",
    emoji: "🚗",
    type: "expense",
    color: "#38bdf8",
  },
  {
    id: "cat-utilities",
    name: "水電瓦斯",
    emoji: "💡",
    type: "expense",
    color: "#facc15",
  },
  {
    id: "cat-communication",
    name: "通訊",
    emoji: "📱",
    type: "expense",
    color: "#22c55e",
  },
  {
    id: "cat-subscription",
    name: "訂閱",
    emoji: "🔄",
    type: "expense",
    color: "#a78bfa",
  },
  {
    id: "cat-clothing",
    name: "服飾",
    emoji: "👕",
    type: "expense",
    color: "#ec4899",
  },
  {
    id: "cat-entertainment",
    name: "休閒娛樂",
    emoji: "🎮",
    type: "expense",
    color: "#8b5cf6",
  },
  {
    id: "cat-healthcare",
    name: "醫療保健",
    emoji: "🏥",
    type: "expense",
    color: "#ef4444",
  },
  {
    id: "cat-other-expense",
    name: "其他",
    emoji: "📦",
    type: "expense",
    color: "#94a3b8",
  },
  {
    id: "cat-loan",
    name: "貸款",
    emoji: "💳",
    type: "expense",
    color: "#48c7a2",
  },
  {
    id: "cat-salary",
    name: "薪資",
    emoji: "💰",
    type: "income",
    color: "#34d399",
  },
  {
    id: "cat-bonus",
    name: "獎金",
    emoji: "🎁",
    type: "income",
    color: "#f472b6",
  },
  {
    id: "cat-subsidy",
    name: "補助",
    emoji: "🏛️",
    type: "income",
    color: "#34d399",
  },
  {
    id: "cat-investment",
    name: "投資",
    emoji: "📈",
    type: "income",
    color: "#10b981",
  },
  {
    id: "cat-gift",
    name: "零用錢、贈與",
    emoji: "❤️",
    type: "income",
    color: "#fb7185",
  },
];

export const transactions = [
  {
    id: "tx-20260501-rent",
    date: "2026-05-01",
    type: "支出",
    category: "住房",
    categoryId: "cat-housing",
    amount: 20000,
    note: "房租",
    sourceType: "recurring",
    recurringId: "recurring-rent",
    expenseType: "fixed",
  },
  {
    id: "tx-20260502-chatgpt",
    date: "2026-05-02",
    type: "支出",
    category: "訂閱",
    categoryId: "cat-subscription",
    amount: 690,
    note: "ChatGPT",
    sourceType: "recurring",
    recurringId: "recurring-chatgpt",
    expenseType: "fixed",
  },
  {
    id: "tx-20260503-subsidy",
    date: "2026-05-03",
    type: "收入",
    category: "補助",
    categoryId: "cat-subsidy",
    amount: 18000,
    note: "保母補助",
    sourceType: "manual",
    recurringId: null,
    expenseType: null,
  },
];

export const recurringRules = [
  {
    id: "recurring-rent",
    name: "房租",
    amount: 20000,
    category: "住房",
    categoryId: "cat-housing",
    frequency: "monthly",
    enabled: true,
  },
  {
    id: "recurring-chatgpt",
    name: "ChatGPT",
    amount: 690,
    category: "訂閱",
    categoryId: "cat-subscription",
    frequency: "monthly",
    enabled: true,
  },
];
