import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { CategoriesProvider } from "./categories-context";
import BottomNav from "./ui/bottom-nav";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col pb-[calc(100px+env(safe-area-inset-bottom))]">
        <CategoriesProvider>{children}</CategoriesProvider>
        <BottomNav />
      </body>
    </html>
  );
}
